# Generated by Django 3.2 on 2022-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220728_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_text',
            field=models.TextField(blank=True),
        ),
    ]
