# Generated by Django 3.2 on 2022-07-28 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20220728_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogstatus',
            unique_together={('blog', 'user')},
        ),
        migrations.RemoveField(
            model_name='blogstatus',
            name='resource',
        ),
    ]
