# Generated by Django 3.2 on 2022-07-29 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogstatus_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstatus',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blog'),
        ),
    ]
