# Generated by Django 3.2.1 on 2022-08-01 13:36

from django.db import migrations
from core.mock_data.mock_data import blogs
from core.models import Blog, Resource


def create_blog_and_resource_object(apps, schema_editor):
    for blog in blogs:
        blog_to_create = Blog(
            blog_title=blog["blog_title"],
            published_date=blog["published_date"],
        )
        blog_to_create.save()
        for resource in blog["resources"]:
            resource_to_create = Resource(
                resource_type=resource["resource_type"],
                resource_link=resource["resource_link"],
                resource_text=resource["resource_text"],
                blog=blog_to_create,
            )
            resource_to_create.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_blogstatus_blog"),
    ]

    operations = [
        migrations.RunPython(
            create_blog_and_resource_object,
            lambda _, x: None,
        ),
    ]
